# Generated by Django 4.1.6 on 2023-02-12 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PreApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos_compra',
            name='descuento',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
