# Generated by Django 4.1.6 on 2023-02-12 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PreApp', '0002_alter_datos_compra_descuento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos_compra',
            name='fecha',
            field=models.DateField(verbose_name='%m/%d/%y'),
        ),
    ]
